global:
  resolve_timeout: 1m
  slack_api_url: $ALERTMANAGER_SLACK_API_URL

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#benchmark-tooling-firehose'
    send_resolved: true
